package com.bagaggio.individual_challenge.exceptions;

public class RecursoNaoEncontradoException extends RuntimeException {
    public RecursoNaoEncontradoException(String msg) {
        super(msg);
    }
}
